### ISSUE TITLE
Track plugin licenses

### ISSUE THREAD

**Issue by MCOfficer** [EndlessSkyCommunity/endless-sky-plugins#19]

**Comment by MCOfficer** [comment]
Notes on the license status of various plug-ins. Not mentioned are those that have a clear `LICENSE` file:

- all-content-plugin: GPL3 license in file headers
- BetterVanillaPirates: Public Domain in copyright.txt
- Ciu-Kreo: GPL-3-or-later in copyright.txt
- ESDefenseDronePlugin: unknown license @starmlerp
- endless-sky-high-dpi: GPL-3+ in copyright.txt
- Epic Trucker: CC-BY-SA-4.0 in copyright.txt
- Flamethrower Turret: GPL-3+ in copyright.txt
- Human Ship Expansion / The-more-ships-plugin: Some files are GPL3'd, rest unknown @loiseeer 
- Korath Automation Upgrade: GPL-3+ in copyright.txt
- The Enclave: unknown license @Makuta-Miras
- World Forge: questionable GPL3 license in file headers, https://github.com/EndlessSkyCommunity/world-forge/pull/60

**Comment by starmlerp** [comment]
My ESDDP is more of a test plugin, letting people experience the content of my [PR](https://github.com/endless-sky/endless-sky/pull/5071) without having to compile the game code from scratch. As such, it'll likely be incompatible (and I'll remove it) with 0..9.13 and later, if it gets merged.
