### ISSUE TITLE
Write a plugin.yaml specification

### ISSUE THREAD

**Issue by MCOfficer** [EndlessSkyCommunity/endless-sky-plugins#20]

**Comment by tehhowch** [comment]
One requirement I have is that the external interface should allow consuming applications to request a version of the generated file spec they know how to handle, i.e. to enable painless breaking changes in how we convert plugin metadata into machine-readable data.

e.g.
```
api/
  v1/
    index.json
    ...
  v2/
    index.json
    ...
```

Obviously we hope to not have breaking changes, but we are human, after all.
